doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'
    server_version: 'mariadb-10.4.32'
    default_table_options:
      charset: utf8mb4
      collate: utf8mb4_general_ci

  orm:
    auto_generate_proxy_classes: true

    mappings:
      App:
        is_bundle: false
        type: attribute
        dir: '%kernel.project_dir%/src/Entity'
        prefix: 'App\Entity'
        alias: App
